---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: admin
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: flux
  rollback:
    enable: true
    retry: true
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.5.0